server:
  port: 8080
app:
  data-dir: data
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      [mail.smtp.auth]: ${MAIL_SMTP_AUTH:false}
      [mail.smtp.starttls.enable]: ${MAIL_SMTP_STARTTLS:false}
