server:
  port: 8080
app:
  data-dir: data
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shadow_ban?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}
          ssl:
            trust: ${MAIL_SMTP_SSL_TRUST:smtp.gmail.com}

logging:
  level:
    org.springframework.boot.autoconfigure.sql: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
