server:
    port: ${PORT:8080}

app:
    data-dir: data

spring:
    datasource:
        url: ${MYSQL_URL}
        username: ${MYSQLUSER}
        password: ${MYSQLPASSWORD}

    jackson:
        serialization:
            write-dates-as-timestamps: false

    sql:
        init:
            mode: always
            schema-locations: classpath:schema.sql
            data-locations: classpath:data.sql

    jpa:
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true

    mail:
        host: ${MAIL_HOST:smtp.gmail.com}
        port: ${MAIL_PORT:587}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    ssl:
                        trust: smtp.gmail.com

logging:
    level:
        org.springframework.jdbc: DEBUG
        org.springframework.boot.autoconfigure.jdbc: DEBUG
